// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package meta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetupTaskRequest struct {
	TaskID               *string  `protobuf:"bytes,1,req,name=TaskID" json:"TaskID,omitempty"`
	HostOsType           *string  `protobuf:"bytes,2,req,name=HostOsType" json:"HostOsType,omitempty"`
	HostOsName           *string  `protobuf:"bytes,3,req,name=HostOsName" json:"HostOsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupTaskRequest) Reset()         { *m = SetupTaskRequest{} }
func (m *SetupTaskRequest) String() string { return proto.CompactTextString(m) }
func (*SetupTaskRequest) ProtoMessage()    {}
func (*SetupTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *SetupTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupTaskRequest.Unmarshal(m, b)
}
func (m *SetupTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupTaskRequest.Marshal(b, m, deterministic)
}
func (m *SetupTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupTaskRequest.Merge(m, src)
}
func (m *SetupTaskRequest) XXX_Size() int {
	return xxx_messageInfo_SetupTaskRequest.Size(m)
}
func (m *SetupTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupTaskRequest proto.InternalMessageInfo

func (m *SetupTaskRequest) GetTaskID() string {
	if m != nil && m.TaskID != nil {
		return *m.TaskID
	}
	return ""
}

func (m *SetupTaskRequest) GetHostOsType() string {
	if m != nil && m.HostOsType != nil {
		return *m.HostOsType
	}
	return ""
}

func (m *SetupTaskRequest) GetHostOsName() string {
	if m != nil && m.HostOsName != nil {
		return *m.HostOsName
	}
	return ""
}

type SetupTaskResponse struct {
	ErrCode              *int32   `protobuf:"varint,1,req,name=ErrCode" json:"ErrCode,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,2,req,name=ErrMsg" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupTaskResponse) Reset()         { *m = SetupTaskResponse{} }
func (m *SetupTaskResponse) String() string { return proto.CompactTextString(m) }
func (*SetupTaskResponse) ProtoMessage()    {}
func (*SetupTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *SetupTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupTaskResponse.Unmarshal(m, b)
}
func (m *SetupTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupTaskResponse.Marshal(b, m, deterministic)
}
func (m *SetupTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupTaskResponse.Merge(m, src)
}
func (m *SetupTaskResponse) XXX_Size() int {
	return xxx_messageInfo_SetupTaskResponse.Size(m)
}
func (m *SetupTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetupTaskResponse proto.InternalMessageInfo

func (m *SetupTaskResponse) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SetupTaskResponse) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

type RemoveTaskRequest struct {
	TaskID               *string  `protobuf:"bytes,1,req,name=TaskID" json:"TaskID,omitempty"`
	UserName             *string  `protobuf:"bytes,2,req,name=UserName" json:"UserName,omitempty"`
	Passwd               *string  `protobuf:"bytes,3,req,name=Passwd" json:"Passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTaskRequest) Reset()         { *m = RemoveTaskRequest{} }
func (m *RemoveTaskRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTaskRequest) ProtoMessage()    {}
func (*RemoveTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{2}
}

func (m *RemoveTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTaskRequest.Unmarshal(m, b)
}
func (m *RemoveTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTaskRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTaskRequest.Merge(m, src)
}
func (m *RemoveTaskRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTaskRequest.Size(m)
}
func (m *RemoveTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTaskRequest proto.InternalMessageInfo

func (m *RemoveTaskRequest) GetTaskID() string {
	if m != nil && m.TaskID != nil {
		return *m.TaskID
	}
	return ""
}

func (m *RemoveTaskRequest) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *RemoveTaskRequest) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

type RemoveTaskResponse struct {
	ErrCode              *int32   `protobuf:"varint,1,req,name=ErrCode" json:"ErrCode,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,2,req,name=ErrMsg" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTaskResponse) Reset()         { *m = RemoveTaskResponse{} }
func (m *RemoveTaskResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTaskResponse) ProtoMessage()    {}
func (*RemoveTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{3}
}

func (m *RemoveTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTaskResponse.Unmarshal(m, b)
}
func (m *RemoveTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTaskResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTaskResponse.Merge(m, src)
}
func (m *RemoveTaskResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTaskResponse.Size(m)
}
func (m *RemoveTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTaskResponse proto.InternalMessageInfo

func (m *RemoveTaskResponse) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *RemoveTaskResponse) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*SetupTaskRequest)(nil), "SetupTaskRequest")
	proto.RegisterType((*SetupTaskResponse)(nil), "SetupTaskResponse")
	proto.RegisterType((*RemoveTaskRequest)(nil), "RemoveTaskRequest")
	proto.RegisterType((*RemoveTaskResponse)(nil), "RemoveTaskResponse")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8e, 0x3d, 0xcb, 0xc2, 0x30,
	0x14, 0x46, 0x79, 0xfb, 0xe2, 0xd7, 0x9d, 0x6c, 0x06, 0x09, 0x0e, 0x22, 0x99, 0x9c, 0xfc, 0x13,
	0x5a, 0xd1, 0xc1, 0x0f, 0x62, 0x9d, 0x25, 0xd0, 0x8b, 0xa0, 0xd4, 0xc4, 0xdc, 0x54, 0xf1, 0xdf,
	0x4b, 0x6a, 0xd4, 0x8c, 0xe2, 0x78, 0xee, 0x43, 0x72, 0x0e, 0x40, 0x89, 0x4e, 0x8d, 0x8d, 0xd5,
	0x4e, 0x8b, 0x23, 0x74, 0xb7, 0xe8, 0x2a, 0x93, 0x2b, 0x3a, 0x49, 0xbc, 0x54, 0x48, 0x8e, 0xf5,
	0xa0, 0xe9, 0x71, 0x31, 0xe5, 0x7f, 0xc3, 0x64, 0xd4, 0x91, 0x81, 0xd8, 0x00, 0x60, 0xae, 0xc9,
	0xad, 0x29, 0xbf, 0x1b, 0xe4, 0x49, 0xbd, 0x45, 0x97, 0xcf, 0xbe, 0x52, 0x25, 0xf2, 0xff, 0x78,
	0xf7, 0x17, 0x91, 0x41, 0x1a, 0xb9, 0xc8, 0xe8, 0x33, 0x21, 0xe3, 0xd0, 0xca, 0xac, 0x9d, 0xe8,
	0x02, 0x6b, 0x5b, 0x43, 0xbe, 0xd0, 0x67, 0x64, 0xd6, 0x2e, 0xe9, 0x10, 0x54, 0x81, 0xc4, 0x1e,
	0x52, 0x89, 0xa5, 0xbe, 0xe2, 0x37, 0xcd, 0x7d, 0x68, 0xef, 0x08, 0x6d, 0x5d, 0xf4, 0xfc, 0xe6,
	0xcd, 0xfe, 0xcd, 0x46, 0x11, 0xdd, 0x8a, 0xd0, 0x1a, 0x48, 0xcc, 0x80, 0xc5, 0x82, 0x5f, 0x43,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0x35, 0x28, 0x97, 0x68, 0x01, 0x00, 0x00,
}
